export { default as BatteryCharge } from './BatteryCharge.svelte'
export { default as Bell } from './Bell.svelte'
export { default as CursiveFont } from './CursiveFont.svelte'
export { default as Contrast } from './Contrast.svelte'
export { default as Devices } from './Devices.svelte'
export { default as Globe } from './Globe.svelte'
export { default as House } from './House.svelte'
export { default as Logout } from './LogOut.svelte'
export { default as Map } from './Map.svelte'
export { default as Medal } from './Medal.svelte'
export { default as Palette } from './Palette.svelte'
export { default as Settings } from './Settings.svelte'
export { default as Shield } from './Shield.svelte'
export { default as Tent } from './Tent.svelte'
export { default as Translate } from './Translate.svelte'

export type { iconComponent } from './type'
